before_script:
  - npm install 
language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
# uncomment and edit the following line if your project needs to run something other than `rake`:
script: gulp buildSDK