before_script:
  - npm install 
language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.0"
  - "0.10"
  - "iojs"
# uncomment and edit the following line if your project needs to run something other than `rake`:
script: gulp buildSDK
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
    code_climate:
        repo_token: f1e9e96a2125b6e278aeed6df6091fa0fd1e04d5a4b0685843a16c25f9b912f2
notifications:
  slack: tradable:XOmWzsyXwAqK3jxRZaESB0ei
after_success:
  - bash <(curl -s https://codecov.io/bash)